### PR TITLE
expandable rows for visit table by grouping

### PR DESCRIPTION
**Pull request by Johngtka**
Show records grouped in expandable rows. Show only first part of the table (more about it in upcoming task).

brave_BJKFqaqNW2

Known problems:
 - lost sticky header
 - lost responsiveness of the table 

# Features List:

- [x] `added new fields in database store endpoint (code, parent)`
- [x] `rebuilded visit table like when store has parent then show parent with all childs rows`
- [x] `the parent row is expandable`
- [x] `added new (more info) column to table`
- [x] `when row was clicked then image zoom in`

### CODE REVIEW

**Comment by Johngtka** [comment]
@macrog whether we will continue this pr?

**Comment by Johngtka** [comment]
> @macrog whether we will continue this pr?

@macrog and how?

**Comment by Johngtka** [comment]
S&M commit proposal:

`feat: new view of visit table (#50)`

**Comment by macrog** [comment]
@Johngtka give it a go, let's see if everything is working as before.

**Comment by macrog** [comment]
checklist:

- [ ] user can select any row
- [ ] user can deselect any row
- [ ] parent row cannot be selected
- [ ] once clicking CHECK button the `visitPoints` are displayed (same flow as before)

**Comment by Johngtka** [comment]
> @Johngtka  please do the checklist (feel free to add any other case):
> 
> - [ ] user can select any row
> - [ ] user can deselect any row
> - [ ] parent row cannot be selected
> - [ ] once clicking CHECK button the `visitPoints` are displayed (same flow as before)

Ok i can check it

**Comment by Johngtka** [comment]
> > @Johngtka  please do the checklist (feel free to add any other case):
> > 
> > - [ ] user can select any row
> > - [ ] user can deselect any row
> > - [ ] parent row cannot be selected
> > - [ ] once clicking CHECK button the `visitPoints` are displayed (same flow as before)
> 
> Ok i can check it

Why lost responsive of table

**Comment by Johngtka** [comment]
@macrog not working correctly events list:

- [ ] `when user recheck the visit table and close the visit then visit table show all rows without expandable parent`

**Comment by Johngtka** [comment]
@macrog I solved the problem of missing the dropdown parent option by adding a getStore reload from the service (again):
just paste it to dialog afterClosed function 
`if (conf === ConfirmationDialogResponse.OK) {
                    this.patient = {} as Patient;
                    this.showCheck = false;
                    this.showFinish = false;
                    this.storeService.getStore().subscribe({
                        next: (data) => {
                            this.store = data;
                            data = orderBy(data, [(v) => v.code]);

                            this.groupReservoirsParents = this.getTableData(
                                data,
                                'R',
                            );
                            this.dataSource = new MatTableDataSource<any>(
                                this.groupReservoirsParents,
                            );
                            this.dataSource.paginator = this.paginator;
                            this.isLoadingResults = false;
                        },
                        error: (err) => {
                            this.snackService.showSnackBarMessage(
                                'ERROR.PATIENT_VISIT_CREATE_PATIENT',
                                SNACK_TYPE.error,
                            );
                            console.log(err.message);
                        },
                    });
                    this.visitPoints = [];
                    console.clear();
                }
            });
        }`

**Comment by Johngtka** [comment]
## Control List:

- [x] user can select any row
- [x] user can deselect any row
- [x] parent row cannot be selected
- [ ] once clicking CHECK button the `visitPoints` are displayed (same flow as before) `tip: the id in backend is a string not number maybe we can change the id to something else`
- [ ] `there is a problem with the lack of drop-down parent rows after closing the visit and checking the selected points` `tip: This can be solved by pasting the getStore call from the service again, as in ngOnInit into the afterClosed dialog`

**Comment by macrog** [comment]
> @macrog not working correctly events list:
> 
> * [x]  `when user recheck the visit table and close the visit then visit table show all rows without expandable parent`
> 
> like this (after research the patient):
> 
> obraz
 
This should be working now

**Comment by macrog** [comment]
> 
> I don't know if this is how the table of marked visit points should be displayed ( in final pdf )
> 
> obraz

At this point yes, we will change it all later

**Comment by macrog** [comment]
@Johngtka please check it again

**Comment by Johngtka** [comment]
> @Johngtka please check it again 

What else??

**Comment by Johngtka** [comment]
> > @macrog not working correctly events list:
> > 
> > * [x]   `when user recheck the visit table and close the visit then visit table show all rows without expandable parent`
> > 
> > like this (after research the patient):
> > obraz
> 
> This should be working now

no it is not working

**Comment by macrog** [comment]
@Johngtka did you pull?

**Comment by Johngtka** [comment]
> @Johngtka did you pull?

Yes but when you write me to recheck changes i Run vsc and did not see the changes for pull

**Comment by Johngtka** [comment]
@macrog all works good bu we could reduce a number of rows in table

**Review by macrog — APPROVED** [review]
👍

**Comment by macrog** [comment]
@Johngtka It's merged, maybe you could do a pull on master and make build please?

**Comment by Johngtka** [comment]
@macrog I'll do the build tomorrow because I have a breakdown of the equipment I'm working on

**Pull request merged**
