### PR TITLE
Visit Flow

### PR DESCRIPTION
**Pull request by Johngtka**
Show `store` data in 3 separate tables with 2 sumary tables in between.

brave_xsMI8SNR66

### CODE REVIEW

**Comment by macrog** [comment]
ok I see that you have a 2 buttons to show different tables. That will work, but we only want to see the button when you get till the end of the first table or second table (if shown)

flow
|table 1 code R |
| ---- |
| points... |

at the end of the table 1 (last page of the table only) show 2 buttons More and Universal (at the end only, the same way we have CHECK button before). **2 possible ways to go**, user clicks More 

**case 1**
show a table with code MR 
|table 2 code MR  |
| ---- |
| points... |
 
at the end of this table show only one button Universal points
when button clicked and anything has been selected in table 1 or table 2 show it in a table

|table 3 summary of table 1 and 2  |
| ---- |
| points... |

if nothing has been selected show table with code P

|table 4 code P  |
| ---- |
| points... |

at the end of this table (last page of the table only), show a button Check and show points that have been selected in table 4

|table 5 summary of table 4  |
| ---- |
| points... |

user still can deselect any points, show button Finish and once clicked show PDF with points from table 5

**case 2**

 user clicks Universal
when button clicked and anything has been selected in table 1 show it in a table

|table 3 summary of table 1  |
| ---- |
| points... |

if nothing has been selected show table with code P

|table 4 code P  |
| ---- |
| points... |

at the end of this table (last page of the table only), show a button Check and show points that have been selected in table 4

|table 5 summary of table 4  |
| ---- |
| points... |

user still can deselect any points, show button Finish and once clicked show PDF with points from table 5

**Comment by macrog** [comment]
@Johngtka check if everything is working as it should please

**Comment by macrog** [comment]
> @Johngtka check if everything is working as it should please

what is going on with this? have you checked?

**Comment by Johngtka** [comment]
> > @Johngtka check if everything is working as it should please
> 
> what is going on with this? have you checked?

Does the check button have a condition to show or is it always shown only that at the end?

**Comment by Johngtka** [comment]
> > > @Johngtka check if everything is working as it should please
> > 
> > 
> > what is going on with this? have you checked?
> 
> Does the check button have a condition to show or is it always shown only that at the end?

because when i do not select any points and move to universal points then i see the check button at the end of table with code P.
simmilary when i am on code P and close the visit and research my self or another patient then i see the table with code R but the paginator is set on last page of this table

**Comment by macrog** [comment]
> > > > > @Johngtka check if everything is working as it should please
> > > > 
> > > > 
> > > > what is going on with this? have you checked?
> > > 
> > > 
> > > Does the check button have a condition to show or is it always shown only that at the end?
> > 
> > 
> > because when i do not select any points and move to universal points then i see the check button at the end of table with code P.
> > simmilary when i am on code P and close the visit and research my self or another patient then i see the table with code R but the paginator is set on last page of this table
> 
> This is first step

can you try to fix the issue then? it's your PR 😄

**Comment by macrog** [comment]
> > > @Johngtka check if everything is working as it should please
> > 
> > 
> > what is going on with this? have you checked?
> 
> Does the check button have a condition to show or is it always shown only that at the end?

always shown at this point

**Comment by Johngtka** [comment]
> > > > > > @Johngtka check if everything is working as it should please
> > > > > 
> > > > > 
> > > > > what is going on with this? have you checked?
> > > > 
> > > > 
> > > > Does the check button have a condition to show or is it always shown only that at the end?
> > > 
> > > 
> > > because when i do not select any points and move to universal points then i see the check button at the end of table with code P.
> > > simmilary when i am on code P and close the visit and research my self or another patient then i see the table with code R but the paginator is set on last page of this table
> > 
> > This is first step
> 
> can you try to fix the issue then? it's your PR 😄 

Nope, because I lost navigation in this component

**Comment by macrog** [comment]
> > > > > > > @Johngtka check if everything is working as it should please
> > > > > > 
> > > > > > 
> > > > > > what is going on with this? have you checked?
> > > > > 
> > > > > 
> > > > > Does the check button have a condition to show or is it always shown only that at the end?
> > > > 
> > > > 
> > > > because when i do not select any points and move to universal points then i see the check button at the end of table with code P.
> > > > simmilary when i am on code P and close the visit and research my self or another patient then i see the table with code R but the paginator is set on last page of this table
> > > 
> > > 
> > > This is first step
> > 
> > 
> > can you try to fix the issue then? it's your PR 😄
> 
> Nope, because I lost navigation in this component @macrog

what? what do you mean you lost navigation in this component? it cannot be more clear at this point what should come after each table, try to understand, this is not a hard task.

**Comment by Johngtka** [comment]
> > > > > > > > @Johngtka check if everything is working as it should please
> > > > > > > 
> > > > > > > 
> > > > > > > what is going on with this? have you checked?
> > > > > > 
> > > > > > 
> > > > > > Does the check button have a condition to show or is it always shown only that at the end?
> > > > > 
> > > > > 
> > > > > because when i do not select any points and move to universal points then i see the check button at the end of table with code P.
> > > > > simmilary when i am on code P and close the visit and research my self or another patient then i see the table with code R but the paginator is set on last page of this table
> > > > 
> > > > 
> > > > This is first step
> > > 
> > > 
> > > can you try to fix the issue then? it's your PR 😄
> > 
> > 
> > Nope, because I lost navigation in this component @macrog
> 
> what? what do you mean you lost navigation in this component? it cannot be more clear at this point what should come after each table, try to understand, this is not a hard task.

i can try that

**Comment by Johngtka** [comment]
| Fisrst search the partiet |
| --- |
| obraz |

 |
\/

**Comment by macrog** [comment]
> @macrog is this correct?
> 
> Fisrst search the partiet	next switch table to code to P (to last page)
> obraz	obraz

That the check button is visible? yes it's correct

**Pull request merged**
